name: CMake Build (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
          submodules: recursive
          
    - name: Install libxrandr-dev
      run: sudo apt-get install -y libxrandr-dev
      
    - name: Install libxinerama-dev
      run: sudo apt-get install -y libxinerama-dev
      
    - name: Install libxcursor-dev
      run: sudo apt-get install -y libxcursor-dev
      
    - name: Install libxi-dev
      run: sudo apt-get install -y libxi-dev
      
    - name: Create Build Folder for GLFW
      working-directory: deps/glfw
      run: mkdir build
    
    - name: Build GLFW
      working-directory: deps/glfw/build
      run: cmake ..
    
    - name: Run Make for GLFW
      working-directory: deps/glfw/build
      run: make 
      
    - name: Install GLFW
      working-directory: deps/glfw/build
      run: make install
      

    - name: Build blank_window
      working-directory: examples/blank_window
      run: cmake ..
      
    - name: Run Make
      working-directory: examples/blank_window
      run: make
